### PR TITLE
Use singleton to properly collect widget groups. Fix #38

### LINKED ISSUE #38: Widget group not being collected on main widget factory instance.
When creating a group widget using the main factory, the groups are not being collected because the factory is using `bind` which always creates a new instance when using `app('arrilot.widget')`. To fix this, I suggest to update the provider to use singleton.

``` php
        $this->app->singleton('arrilot.widget', function () {
            return new WidgetFactory(new LaravelApplicationWrapper());
        });
```

Example snippet to replicate the issue:

``` php
        Widget::all()->groupBy('position')->each(function (Collection $group) {
            $group->each(function ($widget) {
                $factory = app('arrilot.widget');
                $factory->group($widget->position)
                        ->addWidget('widgetManager', [], $widget);
            });
        });
```

To display:

``` php
@widgetGroup('left')
@widgetGroup('right')
```

### PR DESCRIPTION
**Pull request by yajra**

### CODE REVIEW

**Comment by yajra** [comment]
Whoops... Error is on StyleCI and is not related to this PR. Thanks!

**Comment by arrilot** [comment]
I've fixed it in a slightly different way, thanks.

Could you please try version 3.4.0?

Note: use `app('arrilot.widget-group-collection')->group($widget->position)` instead of  `app('arrilot.widget')->group($widget->position)` now

**Comment by yajra** [comment]
@arrilot, using `app('arrilot.widget-group-collection')` did fix the issue. Thanks a lot for the updates! 👍

**Comment by arrilot** [comment]
Nice

**Pull request closed without merging**
