### PR TITLE
Add class aliases for DI

### PR DESCRIPTION
**Pull request by rkgrep**

### CODE REVIEW

**Comment by arrilot** [comment]
Why do we need them if they are already bound into service container?

**Comment by rkgrep** [comment]
To allow all types of injection.

``` php
app(WidgetFactory::class);
// ...
class MyService
{
    // the same for controller methods
    public function __construct(WidgetFactory $widgets)
    {
        //...
    }
}
app(MyService::class);
// ...
```

**Comment by arrilot** [comment]
This is gonna work fine in all current 5.\* releases, isn't it?

**Comment by arrilot** [comment]
I'm a little bit concerned about BC, because i want to support L5.0 as long as possible.

**Comment by rkgrep** [comment]
Yes, it will.
You may split code, compatible with 5.0 into a separate branch.

**Comment by arrilot** [comment]
Thanks for explanation.

**Pull request merged**
